# Generated by Django 5.2 on 2025-05-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedsaccountnumbers_feedscardnumbers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedstypenavigation',
            options={'verbose_name': 'Типы фидов (данных)', 'verbose_name_plural': 'Типы фидов (данных)'},
        ),
        migrations.AlterField(
            model_name='feedsaccountnumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedscardnumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsewalletnumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsfastpaynumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsinn',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsmvdaccountnumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsmvddatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsmvdcardnumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsmvddatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsmvdfastpaynumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsmvddatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsmvdinn',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsmvddatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsmvdpassporthash',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsmvddatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedspassporthash',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsphonenumbers',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedssnilshash',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
        migrations.AlterField(
            model_name='feedsswift',
            name='datedownloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feedsfincertdatedownloads'),
        ),
    ]
