# Generated by Django 5.2 on 2025-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feedstypenavigation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fincertiocdateprocessing',
            name='dateProccesing',
        ),
        migrations.AddField(
            model_name='fincertiocdateprocessing',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Время скачивания фидов'),
        ),
        migrations.AlterField(
            model_name='feedsfincertdatedownloads',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Время скачивания фидов'),
        ),
        migrations.AlterField(
            model_name='feedsmvddatedownloads',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Время скачивания фидов'),
        ),
        migrations.AlterField(
            model_name='fincertiocdateprocessing',
            name='dateMailing',
            field=models.CharField(max_length=30, verbose_name='Дата рассылки IOC'),
        ),
    ]
