# Generated by Django 5.2 on 2025-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_fincertiocdateprocessing_dateproccesing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsaccountnumbers',
            name='accountNumbers',
            field=models.CharField(max_length=64, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='feedsaccountnumbers',
            name='bic',
            field=models.CharField(max_length=65, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='feedscardnumbers',
            name='cardNumbers',
            field=models.CharField(max_length=64, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='feedsewalletnumbers',
            name='ewalletNumbers',
            field=models.CharField(max_length=64, verbose_name='Номер кошелька'),
        ),
        migrations.AlterField(
            model_name='feedsinn',
            name='inn',
            field=models.CharField(max_length=30, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='feedsmvdaccountnumbers',
            name='accountNumbers',
            field=models.CharField(max_length=64, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='feedsmvdcardnumbers',
            name='cardNumbers',
            field=models.CharField(max_length=64, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='feedsmvdfastpaynumbers',
            name='fastpayNumber',
            field=models.CharField(max_length=64, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedsmvdinn',
            name='inn',
            field=models.CharField(max_length=30, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='feedsphonenumbers',
            name='phoneNumbers',
            field=models.CharField(max_length=64, verbose_name='Номер телефона'),
        ),
    ]
