# Generated by Django 5.2 on 2025-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_feedsaccountnumbers_accountnumbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsaccountnumbers',
            name='bic',
            field=models.CharField(max_length=64, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='feedsfastpaynumbers',
            name='fastpayNumber',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
    ]
