# Generated by Django 5.2 on 2025-05-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_feedsaccountnumbers_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsaccountnumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedscardnumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsewalletnumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsfastpaynumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsinn',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsmvdaccountnumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsmvdcardnumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsmvdfastpaynumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsmvdinn',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsmvdpassporthash',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedspassporthash',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsphonenumbers',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedssnilshash',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
        migrations.AddField(
            model_name='feedsswift',
            name='dateExcluded',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления из списка'),
        ),
    ]
