# Generated by Django 5.2 on 2025-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_feedsaccountnumbers_dateexcluded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsmvdaccountnumbers',
            name='bic',
            field=models.CharField(max_length=64, verbose_name='БИК'),
        ),
    ]
