# Generated by Django 5.2.1 on 2025-05-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_feedsmvdaccountnumbers_bic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_view_resource', 'Может просматривать ресурс'), ('can_edit_resource', 'Может редактировать ресурс'), ('can_delete_resource', 'Может удалять ресурс'), ('can_create_resource', 'Может создавать ресурс')],
            },
        ),
    ]
