# Generated by Django 5.2.1 on 2025-05-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
