# Generated by Django 5.2.1 on 2025-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('analyst', 'Аналитик'), ('network_admin', 'Сетевой администратор')], default='analyst', max_length=20, verbose_name='Роль'),
        ),
    ]
