# Generated by Django 5.2.1 on 2025-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('analyst', 'Аналитик'), ('network_admin', 'Сетевой администратор'), ('user', 'Пользователь')], default='analyst', max_length=20, verbose_name='Роль'),
        ),
    ]
