# Generated by Django 5.2.1 on 2025-05-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': [('can_view_resource', 'Может просматривать ресурс')]},
        ),
    ]
