# Generated by Django 5.2.1 on 2025-05-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_resource_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'default_permissions': (), 'permissions': [('can_view_permissions', 'Может просматривать ресурс')]},
        ),
    ]
