# Generated by Django 5.2.1 on 2025-05-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_resource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_view_ioc', 'Может просматривать IOC')],
            },
        ),
        migrations.CreateModel(
            name='MVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_view_mvd', 'Может просматривать МВД')],
            },
        ),
        migrations.RenameModel(
            old_name='Resource',
            new_name='FinCert',
        ),
        migrations.AlterModelOptions(
            name='fincert',
            options={'permissions': [('can_view_fincert', 'Может просматривать FinCert')]},
        ),
        migrations.RenameField(
            model_name='fincert',
            old_name='name',
            new_name='title',
        ),
    ]
