# Generated by Django 5.2.1 on 2025-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_ioc_mvd_rename_resource_fincert_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MVD',
            new_name='Resource',
        ),
        migrations.DeleteModel(
            name='FinCert',
        ),
        migrations.DeleteModel(
            name='IOC',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': [('can_view_mvd', 'Может просматривать МВД'), ('can_view_fincert', 'Может просматривать ФинСерт'), ('can_view_ioc', 'Может просматривать IOC')]},
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='title',
            new_name='name',
        ),
    ]
